### ISSUE TITLE
SourceCode branch only working in Eclipse - not from command line

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/CryptoAnalysis#127]
When I checkout [this branch](https://github.com/CROSSINGTUD/CryptoAnalysis/tree/sourcereader), the analysis works when the projects for [CryptSL](https://github.com/CROSSINGTUD/CryptSL/) are opened at the same time in my eclipse workspace. (Then the classpath includes these projects as eclipse projects  instead of loading the dependency from my local maven repository). 

When I close the CryptSL projects, the dependency for de.darmstadt.tu.crossing.CryptSL-1.0.0-SNAPSHOT.jar is loaded from my local maven repository. And the execution of my tests crash in 

```
com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, org.eclipse.emf.common.util.WrappedException: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.apache.xerces.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
  at org.eclipse.xtext.xbase.services.XtypeGrammarAccess.<init>(XtypeGrammarAccess.java:728)
  at org.eclipse.xtext.xbase.services.XtypeGrammarAccess.class(XtypeGrammarAccess.java:728)
  while locating org.eclipse.xtext.xbase.services.XtypeGrammarAccess
    for parameter 1 at de.darmstadt.tu.crossing.services.CryptSLGrammarAccess.<init>(CryptSLGrammarAccess.java:2317)
  at de.darmstadt.tu.crossing.services.CryptSLGrammarAccess.class(CryptSLGrammarAccess.java:2317)
  while locating de.darmstadt.tu.crossing.services.CryptSLGrammarAccess
  while locating org.eclipse.xtext.IGrammarAccess
    for field at org.eclipse.xtext.linking.lazy.LazyLinker.grammarAccess(LazyLinker.java:300)
  while locating org.eclipse.xtext.linking.lazy.LazyLinker
  while locating org.eclipse.xtext.linking.ILinker
    for field at org.eclipse.xtext.resource.XtextResource.linker(XtextResource.java:461)
  while locating org.eclipse.xtext.linking.lazy.LazyLinkingResource
  while locating org.eclipse.xtext.resource.XtextResource
```

I figured out that the jar file contains a file `CryptSL.xtextbin` which leads to the crash in the analysis. I repackaged the jar file in my local repository such that it does not contain the .xtextbin file any more and the analysis executes without the crash!
However, I did not find a solution how to automatically exclude the file while packaging the .jar file. I tried changing the options in the maven-assembly plugin,  I also tried chaging the tycho-packaging-plugin configuration. 

No effect.

@kruegers Any thoughts on how we could exclude the file from being packaged?

**Comment by johspaeth** [comment]
I added a script with the intention to automatically repackage the jar without the particular file.

The script repackage.sh in [this commit](https://github.com/CROSSINGTUD/CryptSL/commit/aee09c5e2da5ca176d5fdb800077d723907564be) removes the file. The script should be executed via the 
exec-maven-plugin during the maven build. I changed the pom.xml in the commit accordingly.

Unfortunately, the maven build crashes when executing the script:

Cannot run program "...\CryptSL\repackage.sh" (in directory "
\CryptSL\de.darmstadt.tu.crossing.CryptSL"): CreateProcess error=193, %1 ist kei
ne zulõssige Win32-Anwendung -> [Help 1]

**Comment by johspaeth** [comment]
Note. For building this branch I required to update the metadata of my maven
`mvn clean install -U`

**Comment by johspaeth** [comment]
With the latest SNAPSHOT of CryptSL, the sourcereader branched executed a test case (at least until I saw



```
javax.crypto.SecretKeyFactory
forbiddenMethods:
Usage Pattern:Name: -1
Name: 1 (accepting)
Name: 0
Left: -1 ====[javax.crypto.SecretKeyFactory.getInstance( algorithm);, javax.crypto.SecretKeyFactory.getInstance( algorithm _);]====> Right:0
Left: 0 ====[key = javax.crypto.SecretKeyFactory.generateSecret( keySpec);, key = javax.crypto.SecretKeyFactory.translateKey( otherKey);]====> Right:1

Constraints:VC:algorithm - PBEWithHmacSHA512AndAES_128,PBEWithHmacSHA384AndAES_128,PBEWithHmacSHA384AndAES_128,PBKDF2WithHmacSHA224,PBKDF2WithHmacSHA256,PBKDF2WithHmacSHA384,PBKDF2WithHmacSHA512,PBEWithHmacSHA224AndAES_128,PBEWithHmacSHA256AndAES_128,PBEWithHmacSHA224AndAES_256,PBEWithHmacSHA256AndAES_256,PBEWithHmacSHA384AndAES_256,PBEWithHmacSHA512AndAES_256,,VC:algorithm - PBEWithHmacSHA224AndAES_128,PBEWithHmacSHA256AndAES_128,PBEWithHmacSHA512AndAES_128,andVC:keylength - 128,,VC:algorithm - PBEWithHmacSHA224AndAES_256,PBEWithHmacSHA256AndAES_256,PBEWithHmacSHA384AndAES_256,PBEWithHmacSHA512AndAES_256,andVC:keylength - 256,,VC:algorithm - PBKDF2WithHmacSHA224,PBKDF2WithHmacSHA256,PBKDF2WithHmacSHA384,PBKDF2WithHmacSHA512,andVC:keylength - 128,192,256,,speccedKey(keySpec,_),
Predicates:generatedKey(key,algorithm),
```

**Comment by kruegers** [comment]
Nope. Does not work for me. I pulled the branch, closed all related projects, and finally updated the project as you described. Regardless of whether I am running the test cases in the terminal or in Eclipse, I'm still getting the ProvisionException.

**Comment by kruegers** [comment]
Closing this one because it has thankfully been resolved a long time ago.
