### ISSUE TITLE
Analysis does not find that the seed of SecureRandom is static

### ISSUE THREAD

**Issue by enriozuni** [CROSSINGTUD/CryptoAnalysis#140]
The analysis does not correctly check that the seed of a SecureRandom object is not properly randomized. The CrySL rule for [SecureRandom](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/master/JavaCryptographicArchitecture/src/SecureRandom.cryptsl#L42) states that the seed must be randomized, but this requirement is not checked. <br>

The following headless and usage pattern test cases show that the error is not revealed after the analysis:
### [Usage Pattern test case](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/randomgen_demo/CryptoAnalysis/src/test/java/tests/pattern/UsagePatternTest.java#L1225)

**Comment by johspaeth** [comment]
The problem originates from the fact that CryptSLPredicate do not have a proper hashCode and equals method. A predicate A is equal to a predicate B if only A and B's predicate names match. *The parameters (and the base object) are ignored.*. Therefore, all ENSURED and REQUIRED predicates of the [SecureRandom rule](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/master/JavaCryptographicArchitecture/src/SecureRandom.cryptsl) are the same.

When we [implement a hashCode and equals method](https://github.com/CROSSINGTUD/CryptoAnalysis/commit/4ffdb08149d3adaef797e9f9c1fe3052a2568bea) that takes parameter names into account, the test cases @enriozuni described do not fail anymore, [but many others do](
https://soot-build.cs.uni-paderborn.de/jenkins/blue/organizations/jenkins/boomerang%2FCryptoAnalysis-Multibranch/detail/randomgen_demo/2/tests).

I debugged a first one (UsagePatternTestInter1) and noticed that the REQUIRED predicate for the Cipher rule is stated as `generatedKey[key, part(0, "/", transformation)];` whereas the KeyGenerator rule generates `generatedKey[key, alg];`. When are these predicates the same, when aren't they?

We need a better logic to decide that two predicates are equal. @kruegers can we use the types of the parameters to uniquely identify a predicate? Can you implement it?

**Comment by johspaeth** [comment]
We could make `equals` depend on the types of the arguments, if we also were to move the `part(0,"/", transformation)` logic to the `OBJECT` section as I described in https://github.com/CROSSINGTUD/CryptSL/issues/16
