### ISSUE TITLE
Provider Detection analysis does not work when using ObservableDynamicICFG

### ISSUE THREAD

**Issue by enriozuni** [CROSSINGTUD/CryptoAnalysis#142]
The control-flow graph being used in the analysis has changed lately from `JimpleBasedInterproceduralCFG` to `ObservableDynamicICFG`.

The Provider Detection analysis is not working correctly now when the provider is of type `java.security.Provider` as the Boomerang solver does not return any allocation sites anymore, hinting that there is no provider detected where in fact there is.

This is the [link](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/814c23de5347eedee52870a6d85e479ae9985d2c/CryptoAnalysis/src/main/java/crypto/providerdetection/ProviderDetection.java#L280) to the latest commit on the file that does the Provider Detection analysis and fails to detect the provider when is of type `java.security.Provider`

This is the [link](https://github.com/CROSSINGTUD/CryptoAnalysis/pull/128/commits/814c23de5347eedee52870a6d85e479ae9985d2c) of the latest commit on the Pull request

**Comment by johspaeth** [comment]
I updated the dependency of SPDS, which [required a fix](https://github.com/CROSSINGTUD/WPDS/commit/30f091409d56266c0b4a4387fb33c8ee355f682f).
