### ISSUE TITLE
Update to work with Java >=9 projects

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/CryptoAnalysis#143]
Steps to update CryptoAnalysis to work with Java >= 9 projects:

1. Checkout
https://github.com/CROSSINGTUD/WPDS
2. Find all dependencies (see pom.xmls) to soot and update them to soot-j9 version 4.0.0-SNAPSHOT
https://soot-build.cs.uni-paderborn.de/nexus/#browse/browse:soot-snapshot:ca%2Fmcgill%2Fsable%2Fsoot-j9%2F4.0.0-SNAPSHOT
(2a. Make a pull request) 
4. Update [soot version](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/60358d4ecfd59aeead4d56c8a06256cc7b9ccec9/CryptoAnalysis/pom.xml#L103) of CryptoAnalysis respectively.
5.  Create Headless Test with a maven project that uses a Java compiler >= 9
6. Get analysis running on the project. 

Some notes for 6.
* Starting Java 9 there aren't any .jar files in the Java Home folder anymore and we need to pass the String `VIRTUAL_FS_FOR_JDK` to the [soot class path](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/ffb8cc9424ab07f2491b480ea7a0b54b8791f962/CryptoAnalysis/src/main/java/crypto/HeadlessCryptoScanner.java#L330).
* If the target program that we analyse was compile with a version >= 9, the jce.jar shall not be [prepended anymore](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/ffb8cc9424ab07f2491b480ea7a0b54b8791f962/CryptoAnalysis/src/main/java/crypto/HeadlessCryptoScanner.java#L402) to the class path.

**Comment by rakshitkr** [comment]
@johspaeth Kindly close this issue if no further changes are needed.
