### ISSUE TITLE
Data-flow paths for all checked Constraints / RequiredPredicates...

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/CryptoAnalysis#144]
... and not only when a violation occured

At the moment the API only allows to highlight a data-flow path along which the analysis found an error.

Example: 
```
if (...){
    y = "AES/CBC/PKCS5Padding"; (1)
} else {
    y = "AES"; (2)
}
Cipher.getInstance(y) (3)
```
For the violation at (3) one can retrieve "the data-flow path" of statement (2), because the allocated value violates the constraints. But it is impossible to get that "the data-flow path" to (1) that does *not* violate the constraint.

Task:
Enhance `ErrorWithObjectAllocation` to also deliver the data-flow path of all *other* object allocations.

**Comment by johspaeth** [comment]
The new feature is avaliable in the [all-path branch](https://github.com/CROSSINGTUD/CryptoAnalysis/tree/all-path). The features only works for ConstraintErrors. For ConstraintErrors offers an additional function `getAllDataFlowPaths` which outputs the set of relevant statements for all other checked constraints.

The feature is difficult to implement for non ConstraintErrors. ConstraintErrors stem from a backward-directed analysis. The backward-directed analysis computes all allocation sites (or String definitions) and checks each allocation site individually if a constraint is violated. Therefore, the set of statements that may lead to the constraint error is readily available. 
Non-ConstraintErrors are results of a forward-directed analysis (typestate analysis). The forward directed analysis only visits relevant statements in the first place. 

Example

```
Cipher c;
if(...){
    c = Cipher.getInstance("...") (1)
    x = c;  (2)
} else{
    c = null; (3)
    y =c; (4)
}
c.init();
```

A forward-analysis never visits the else branch, as the object never flows through it. @SvenEV let's discuss this further.

**Comment by SvenEV** [comment]
Great, I'll try this out later. I think limiting the feature to ConstraintErrors is not an issue, I'm not even sure what one would expect from `getAllDataFlowPaths` on TypestateErrors. I will write a few tests and let you know how well things work.

**Comment by SvenEV** [comment]
In a first try, I don't seem to get the desired results from `getAllDataFlowPaths`. Here's the code I analyzed:
```java
void check(boolean c) {
    String x = "A"; // A
    String y = "B"; // B
    if (c)
        y = x; // A
    Cipher.getInstance(y); // A, B
}
```

I think this has to do with the way multiple `additionalBoomerangQuery`-s are solved one after another: https://github.com/CROSSINGTUD/CryptoAnalysis/blob/22b4f34b9636bb41293c86cf603101aa61996323/CryptoAnalysis/src/main/java/crypto/extractparameter/ExtractParameterAnalysis.java#L78-L80

I don't really understand the details here, but it looks like the results of each query are treated separately and are not combined. In my example, `additionalBoomerangQuery` has two entries. In the first query, only the allocation site "A" is found and `getAllDataFlowPaths` on the "A"-error only returns the "A"-statements. Analogously, the second query results in only the allocation site "B". If we only had a single query with both allocation sites, it would work I guess.

**Comment by johspaeth** [comment]
The issue is that when you trigger a backward query `y@Cipher.getInstance(y)`, the analysis actually triggers two queries. One for each control-flow successor of the statement, i.e. one for `y = x;` and one at `if(c)`. There results are not merged. I cannot promise you to fix that quicky. But a simple workaround is to add a statement which is unrelated to your data-flow.

```
void check(boolean c) {
    String x = "A"; // A
    String y = "B"; // B
    if (c)
        y = x; // A
    int z = 1;
    Cipher.getInstance(y); // A, B
}

```

**Comment by SvenEV** [comment]
Thanks, the workaround is perfectly sufficient for my needs, no need for you to invest more time in this.
