### ISSUE TITLE
Analysis reports NeverTypeOfError when in fact there is not

### ISSUE THREAD

**Issue by enriozuni** [CROSSINGTUD/CryptoAnalysis#166]
In various CryptoGuard projects in issue #134 that were headless tested, there is a misuse happening often. The analysis reports a NeverTypeOfError for variable being a String, when in fact it is not. I have listed below the projects and the objects from the JCA that were present in these cases.

# CryptoGuard projects and their respective cases
Below are cases that were headless tested. They are grouped according to their project name in CryptoGuard and the JCA object involved.
* __predictablekeystorepassword__ _(KeyStore)_
```java
package example.predictablekeystorepassword;

import java.io.IOException;
import java.net.URL;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;

public class PredictableKeyStorePasswordABICase1 {
    URL cacerts;
    public static void main(String args[]) throws KeyStoreException, IOException, CertificateException, NoSuchAlgorithmException {
        PredictableKeyStorePasswordABICase1 pksp = new PredictableKeyStorePasswordABICase1();
        String key = "changeit";
        pksp.go(key);
    }

    public void go(String key) throws KeyStoreException, IOException, CertificateException, NoSuchAlgorithmException {
        String type = "JKS";
        KeyStore ks = KeyStore.getInstance(type);
        cacerts = new URL("https://www.google.com");
        ks.load(cacerts.openStream(), key.toCharArray());
    }
}
```

Misuse reported is found below:
```
in Method: void go(java.lang.String)
		NeverTypeOfError violating CrySL rule for java.security.KeyStore (on Object #765554a8af8fb873ba5705fc66618bcd781a98f1f8b3b64d97ab0d54dc93c014)
			Second parameter should never be of type java.lang.String.
			at statement: virtualinvoke r3.<java.security.KeyStore: void load(java.io.InputStream,char[])>($r6, $r7)

```
Analysis reports NeverTypeOfError for second param of KeyStore being a String, although it is a character.

* __predictablepbepassword__ _(PBEKeySpec)_
Other similar cases are found in the following [project](https://github.com/CryptoGuardOSS/cryptoapi-bench/tree/master/src/main/java/org/cryptoapi/bench/predictablepbepassword)

**Comment by johspaeth** [comment]
The finding is correct:

The key should be supplied as `char[]` and may not be converted from a `String` via `toCharArray()`.

**Comment by enriozuni** [comment]
@johspaeth OK, then I am gonna update the headless test cases accordingly
