### ISSUE TITLE
Migration from CrySL binary format to source format

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/CryptoAnalysis#176]
We can handle rules in source format (#42) now. Please remove all code related to the binary format.

@kruegers can you point @rakshitkr to files that can be removed?

**Comment by kruegers** [comment]
The class that is mirrored in both CogniCrypt and CogniCrypt<sub>SAST</sub> is the CrySL parser. In the plugin, it is called CrySLModelReader and may be found [here](https://github.com/eclipse-cognicrypt/CogniCrypt/tree/develop/plugins/de.cognicrypt.crysl.handler/src/main/java/de/cognicrypt/crysl/reader). In CogniCrypt<sub>SAST</sub>, the same classes are located [here]( https://github.com/CROSSINGTUD/CryptoAnalysis/tree/develop/CryptoAnalysis/src/main/java/crypto/cryptslhandler]. 

Please remove the classes from the plugin without removing the functionality. That is, make the crysl reader in CogniCrypt<sub>SAST</sub> accessible to the plugin.
