### ISSUE TITLE
No error for call of forbidden methods

### ISSUE THREAD

**Issue by AndreSonntag** [CROSSINGTUD/CryptoAnalysis#177]
The analysis does not detect an error when calling **forbidden calls**. I recogniced the problem through following code:

```
public static void main(String[] args) throws NoSuchAlgorithmException, SignatureException, InvalidKeyException, InvalidKeySpecException {
		
char[] password = new char[]{'c','h','a','r','a','r','r','a','y'};
SecretKeyFactory keyFact = SecretKeyFactory.getInstance("PBEWithHmacSHA512AndAES_128");

PBEKeySpec keySpecA = new PBEKeySpec(password);	//forbidden constructor		
PBEKeySpec keySpecB = new PBEKeySpec(new char[]{'c','h','a','r','a','r','r','a','y'});  //same

SecretKey keyA = keyFact.generateSecret(keySpecA);	
SecretKey keyB = keyFact.generateSecret(keySpecB);
	   
byte[] keyAbyte = keyA.getEncoded();
byte[] keyBbyte = keyB.getEncoded();

keySpecA.clearPassword();
keySpecB.clearPassword();
}

```
Instead of a **ForbiddenMethodError**, I got an **RequiredPredicateError** for line `SecretKey keyA = keyFact.generateSecret(keySpecA);` and an TypeStateError for line `SecretKey keyB = keyFact.generateSecret(keySpecB);`

Version: CryptoAnalysis 2.4-SNAPSHOT

**Comment by Projucti** [comment]
Tested it with the current version 2.8 and got an ForbiddenMethodError, which is a expected behaviour. the problem was with PBKeySpec which doesn't exist anymore. So, the issue can be closed.
