### ISSUE TITLE
Test Failures on Jenkins Server

### ISSUE THREAD

**Issue by kruegers** [CROSSINGTUD/CryptoAnalysis#190]
There are still four test cases failing on the CI. Please check out the [console output](https://soot-build.cs.upb.de/jenkins/job/boomerang/job/CryptoAnalysis-Multibranch/job/develop/64/consoleFull) and investiage the matter further. Thanks.
I cannot reproduce the three BouncyCastle test-case failures on my machine, the JCA unit test fails on machine with the exact error as well.
(Full-text search for 'runtime' gets you to the relevant parts of the file.)

**Comment by rakshitkr** [comment]
@kruegers All the test cases are passing now.
