### ISSUE TITLE
Add possibility to output results into a standard format

### ISSUE THREAD

**Issue by akwick** [CROSSINGTUD/CryptoAnalysis#226]
For further analyzing or working with the results of CogniCrypt, a feature to write the CogniCrypt report in a standard format, e.g, CSV, JSON, or YAML, would be helpful.

**Comment by seena-mathew** [comment]
Implemented the feature for generating the CogniCrypt report in JSON and CSV format. Also added an option for selecting the format of the report to be generated after the analysis.
@akwick, Could you please explain the need for having a YAML report.

**Comment by seena-mathew** [comment]
@akwick The result of Cryptoanalysis is also available in SARIF format.  SARIF is a static analysis exchange format and CryptoAnalysis can already output it as .json. Could you please suggest if the report needs to be generated in other formats as well?

**Comment by akwick** [comment]
Thanks for implementing it. I don't think we need to generate it into other formats as well. I just listed some formats. ;)

**Comment by krinara86** [comment]
Closing this as the required format is already part of the output options.
