### ISSUE TITLE
Keep Maven dependencies up to date

### ISSUE THREAD

**Issue by AndreSonntag** [CROSSINGTUD/CryptoAnalysis#229]
The GitHub app Dependabot is a little useful app which creates automatically pull requests to keep dependencies secure and up-to-date.

https://dependabot.com/

![image](https://user-images.githubusercontent.com/31883471/78769424-a4c5d680-798d-11ea-9de5-ab8ca11b6529.png)

**Comment by kruegers** [comment]
Done. Thanks for the suggestion.
