### ISSUE TITLE
The build of develop branch is failing on Jenkins

### ISSUE THREAD

**Issue by enriozuni** [CROSSINGTUD/CryptoAnalysis#240]
The build of develop branch on Jenkins is failing. The reason is due to an OutOfMemoryError thrown by Maven. This means that the JVM (Jenkins) that is running the project has run out of memory. Currently, a max 8GB of memory is reserved for CryptoAnalysis. After increasing the max memory to 16GB, the error is still persisting. Moreover, the build is successfully completing when I run it locally on my machine with a max of 8GB of memory.

**Comment by johspaeth** [comment]
@enriozuni 
Downgrade the maven-surefire-plugin to version 2.19.1. should work, at least it did locally on my machine. It seems to be bug of Version 2.20 other encountered earlier as well:

https://github.com/junit-team/junit5/issues/809

**Comment by enriozuni** [comment]
@johspaeth Thanks for the suggestion. I will try that.

**Comment by enriozuni** [comment]
I downgraded the maven-surefire-plugin to 2.19.1 and it is still failing on Jenkins. The build completes succesfully on my machine. I get the same error in all test cases in Jenkins: 
`java.lang.ClassCastException: de.darmstadt.tu.crossing.crySL.impl.SuperTypeImpl cannot be cast to de.darmstadt.tu.crossing.crySL.impl.ObjectImpl`

The funny thing is that nowhere in the code (CryptoAnalysis or elsewhere) there is such casting operation for it to be throwing this exception. I initially doubted that maybe there is some outdated dependency saved locally on Jenkins and the build is using that (and thus causing the error), but the whole build process is running with the `-U` option that fetches everything directly from remote servers.
