### ISSUE TITLE
Exceptions on running just after cloning the project

### ISSUE THREAD

**Issue by roxennnn** [CROSSINGTUD/CryptoAnalysis#263]
Hi, 

I wanted to test your project, so I cloned your repository and followed your guide from the `README.md`. However, when I run the following command, 
```
java -cp CryptoAnalysis/build/CryptoAnalysis-2.7.3-SNAPSHOT-jar-with-dependencies.jar crypto.HeadlessCryptoScanner   --rulesDir=$(pwd)/CryptoAnalysis/src/main/resources/JavaCryptographicArchitecture   --applicationCp=$(pwd)/CryptoAnalysisTargets/CogniCryptDemoExample/Examples.jar
```
I obtain the error that you can see from the attached file:

[CryptoAnalysisExceptions.txt](https://github.com/CROSSINGTUD/CryptoAnalysis/files/4711746/CryptoAnalysisExceptions.txt)

I have also tried to download and run your pre-compiled version, but I get the same errors. 

Could you please tell me what I did wrong?

**Comment by johspaeth** [comment]
I assume you are running on JDK 13 or JDK 14. 

It is is an issue in Soot that we only recently [merged into Soot](https://github.com/Sable/soot/tree/jdk14_fix) and we haven't updated the soot version on CryptoAnalysis yet.

Can you use an JDK < 13?

**Comment by roxennnn** [comment]
I was in fact using JDK 13. I downgraded to JDK 11 and I confirm it works now. 

Thank you!
