### ISSUE TITLE
Custom rules not handled as expected

### ISSUE THREAD

**Issue by krinara86** [CROSSINGTUD/CryptoAnalysis#299]
Assume I have a custom rule set (bunch of crysl rules) with constraints, orders etc. And I add both the API jar, and the crysl rules to the build path in CogniCrypt. Only constraint errors are detected, but order errors are not detected. In the background, I get the following warnings, I suspect this has something to do with the typestate implementation of SAST.
<img width="1354" alt="Screenshot 2020-10-05 at 09 48 37" src="https://user-images.githubusercontent.com/59579968/95052896-f6a6a980-06ef-11eb-9af9-63ec6b3a43d4.png">

How the issue looks like :
<img width="903" alt="Screenshot 2020-10-05 at 09 19 22" src="https://user-images.githubusercontent.com/59579968/95052950-06be8900-06f0-11eb-9aab-64db0446a002.png">

How to reproduce the issue:
1) Download the  testQTeslaProject.zip file
2) Open it as a java project with an Eclipse containing the CogniCrypt plugin. 
3) Run crypto analysis on the project.

[testQTeslaProject.zip](https://github.com/CROSSINGTUD/CryptoAnalysis/files/5325952/testQTeslaProject.zip)

**Comment by enriozuni** [comment]
This issue is solved with eclipse-cognicrypt/CogniCrypt#417 so it can be closed.
