### ISSUE TITLE
Exception Handling is not considered correctly

### ISSUE THREAD

**Issue by steffsas** [CROSSINGTUD/CryptoAnalysis#315]
**Prerequisites**
Currently, I'm testing the CryptoAnalysis on non-crypto APIs. Therefore, I wrote a custom CrySL rule for java.io.FileReader, for testing purposes only. Custom CrySL rules are recognized.

**Bug**
Assume the following example:
![grafik](https://user-images.githubusercontent.com/32709406/99814808-ca34d880-2b49-11eb-8837-e2506ac9b2cd.png)

With the following simple CrySL rule:
![grafik](https://user-images.githubusercontent.com/32709406/99814494-5692cb80-2b49-11eb-81b2-740b48c9af17.png)

Although this example is correct, it seems there is a problem with path-insensitivity also in try-catch blocks. The following error is displayed at line 253:

`Operation on object of type java.io.FileReader object not completed. Expected call to java.lang.AutoCloseable: void close(), read, java.io.Reader: void close(), java.io.Closeable: void close(), java.io.FileReader: void close(), java.io.InputStreamReader: void close()`

**Please also consider finally blocks!**

**Comment by smeyer198** [comment]
Fixed in #480. The problem was that the class `FileReader` does not define the methods `read` and `close` itself, but inherites them from superclasses or superinterfaces.
