### ISSUE TITLE
Cannot specify forbidden methods with argument String

### ISSUE THREAD

**Issue by steffsas** [CROSSINGTUD/CryptoAnalysis#317]
**Prerequisites**
Currently, I'm testing the CryptoAnalysis on non-crypto APIs. Therefore, I wrote a custom CrySL rule for java.text.SimpleDateFormat for testing purposes only. Custom CrySL rules are recognized.

**Bug**
I want to specify a forbidden constructor method with the parameter String (java.lang.String). It's neither working with simply String nor with java.lang.String. It seems there is a resolution error with non-primitive types. Resolution works, for example, in the EVENTS section.

![grafik](https://user-images.githubusercontent.com/32709406/99940975-84585a00-2d6d-11eb-8de7-d15e18d7cbb1.png)
![grafik](https://user-images.githubusercontent.com/32709406/99941035-9f2ace80-2d6d-11eb-8ee8-fd877a88fe98.png)

**Comment by smeyer198** [comment]
Fixed in CrySL 3.0.0 and CryptoAnalysis 3.0.0 (#480)
