### ISSUE TITLE
False Positive TypestateError in Cipher Class

### ISSUE THREAD

**Issue by LWintr** [CROSSINGTUD/CryptoAnalysis#364]
When working with the javax.crypto.Cipher Class a TypestateError is produced, which does not seem to fit the CrySL rule.
The problem occurs when working with Latest Release 2.7.2 as well as the current develop version.
Already discussed the issue with @akwick and @schlichtig today.

Example Code:
![grafik](https://user-images.githubusercontent.com/85743537/136584196-fd8c573c-784e-4e85-9738-d37677709198.png)

Error:
![grafik](https://user-images.githubusercontent.com/85743537/136584359-c30d4236-a701-4dbf-ba79-5063640edfa6.png)

Order Section of Cipher Rule
![grafik](https://user-images.githubusercontent.com/85743537/136584432-d8a0f60a-5e34-4cc1-8c28-555e822a3a34.png)

**Comment by anemonekk** [comment]
A possible fault in the statmachine building logic might cause this error, but has not been validated yet. I added a comment for this in line 235 in class StatemachineGraphBuilder in the following PR: https://github.com/CROSSINGTUD/CryptoAnalysis/pull/366

**Comment by svenfeld** [comment]
Due to this error and the importance of the Cipher class the AADUpdates is removed from the corresponding crysl rules by this CROSSINGTUD/Crypto-API-Rules#110 PR. The mentioned PR can be reverted if this error is resolved.

**Comment by schlichtig** [comment]
[https://github.com/CROSSINGTUD/CryptoAnalysis/pull/377](https://github.com/CROSSINGTUD/CryptoAnalysis/pull/377) fixes this issue
