### ISSUE TITLE
False Positive RequiredPredicateError when woking with JCA PBE

### ISSUE THREAD

**Issue by LWintr** [CROSSINGTUD/CryptoAnalysis#367]
When working with Password-Based Encryption in the JCA I noticed a possible False-positive when analyzing with CryptoAnalysis 2.7.2 release.
The issue seems to persist in the current development version. (I tested 2.7.2 with 2.7.2 ruleset and develop with the current ruleset from the Crypto-API-Rule project)

    public class Main {
  
	  public static void main(String[] args) throws NoSuchAlgorithmException, InvalidKeySpecException, NoSuchPaddingException, InvalidKeyException, InvalidAlgorithmParameterException, IllegalBlockSizeException, BadPaddingException, UnsupportedEncodingException {
		  PBEKeySpec pbeKeySpec;
		  PBEParameterSpec pbeParamSpec;
		  SecretKeyFactory keyFac;
		  
		  byte[] salt = new byte[16];
		  new SecureRandom().nextBytes(salt);
		  
		  byte[] ivBytes = new byte[16];
		  new SecureRandom().nextBytes(ivBytes);
		  IvParameterSpec ivSpec = new IvParameterSpec(ivBytes);
		  
		  int count = 10000;
		  
		  pbeParamSpec = new PBEParameterSpec(salt, count, ivSpec);
		  char[] password = {'a', 'b', 'c', 'd', 'e'};
		  pbeKeySpec = new PBEKeySpec(password, salt, count, 256);
		  keyFac = SecretKeyFactory.getInstance("PBEWithHmacSHA256AndAES_256");
		  SecretKey pbeKey = keyFac.generateSecret(pbeKeySpec);
		  // Encryption
		  Cipher pbeEncryptionCipher = Cipher.getInstance("PBEWithHmacSHA256AndAES_256/CBC/PKCS5Padding");
		  pbeEncryptionCipher.init(Cipher.ENCRYPT_MODE, pbeKey, pbeParamSpec);
		  byte[] cleartext = "This is an example".getBytes("UTF-8");
		  byte[] ciphertext = pbeEncryptionCipher.doFinal(cleartext);
		  // Decryption
		  Cipher pbeDecryptionCipher = Cipher.getInstance("PBEWithHmacSHA256AndAES_256/CBC/PKCS5Padding");
		  pbeDecryptionCipher.init(Cipher.DECRYPT_MODE, pbeKey, pbeParamSpec);
		  byte[] decryptedText = pbeDecryptionCipher.doFinal(ciphertext);
		  System.out.println("Received: " + new String(decryptedText, "UTF-8"));
		  
		  pbeKeySpec.clearPassword();	
	  }
  
    }

CryptoAnalysis lists the following error:

    RequiredPredicateError violating CrySL rule for javax.crypto.Cipher
              Third parameter was not properly generated as prepared I V
              at statement: virtualinvoke r14.<javax.crypto.Cipher: void init(int,java.security.Key,java.security.spec.AlgorithmParameterSpec)>(varReplacer7, r13, r7)

CryptoAnalysis does not list this error anymore if I replace the PBEParameterSpec in the Cipher.init calls with the IvParameterSpec. But the code can not be compiled like this.
CA "fails to recognize" that the correctly generated IvParameterSpec is contained within the PBEParameterSpec in this case.

I will include the .java and .class file with this issue.
[Code.zip](https://github.com/CROSSINGTUD/CryptoAnalysis/files/7691803/Code.zip)

**Comment by marvinvo** [comment]
Hi, that is an issue with the Crypto-API Rules. 

Your transformation is the string: "PBEWithHmacSHA256AndAES_256/CBC/PKCS5Padding".
So mode(transformation) will return "CBC".

But lets have a look at the Cipher.crysl:
https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/1dbad342a46c47df62e891fc25f46944972d9e18/JavaCryptographicArchitecture/src/Cipher.crysl#L138

As you can see in the REQUIRED section, with mode(transformation)="CBC", CrySL actually requires 
preparedIV[paramSpec]. That is obviously not true if your code is secure too.
