### ISSUE TITLE
No delete button for custom rules

### ISSUE THREAD

**Issue by shahrzadav** [CROSSINGTUD/CryptoAnalysis#369]
There is an option in the preference page of CogniCrypt that allows users to add local or remote rulesets. The problem is there is no button to delete or edit these. When too many rulesets are added, the preference page may crash.

**Comment by AnakinSklavenwalker** [comment]
Is this a feature CryptoAnalysis is lacking? Cause otherwise this sounds like a ticket for CogniCrypt Eclipse Plugin and not CryptoAnalysis.

**Comment by shahrzadav** [comment]
@AnakinSklavenwalker @schlichtig Sure I will move it to CogniCrypt.
