### ISSUE TITLE
Parse and read-in CrySL rules in source code format

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/CryptoAnalysis#42]
CogniCrypt_SAST requires CrySL rules in binary format (cryptslbin) as input. The binary format can only be produced by the eclipse plugin CogniCrypt. To make CogniCrypt_SAST more user-friendly, it should accept CrySL rules in source code format as input.

**Comment by kruegers** [comment]
Well, in order to do that, we either need the Cry(pt)SL plugin because that's where the parser is or write our own CrySL parser based on the grammar. The former comes with Eclipse dependencies, the latter sounds quite nasty, especially since we have to keep it up-to-date.
Would you want to invest time in that anyways?

**Comment by johspaeth** [comment]
I would like to have the analysis independent from an Eclipse instance, that's all. Even if this means including some of the Eclipse dependencies, I am ok with that. Couldn't that work if we include the CryptSL plugin as a dependency? There [seems to be a way](http://www.davehofmann.de/different-ways-of-parsing-with-xtext/) to use Xtext as standalone.

**Comment by johspaeth** [comment]
Are you still working on this? When do you have the time to finish it? 
I would like to minize the rule set to rules with little false positives, but don't want to go the whole way of modifying the rules in eclipse.

**Comment by kruegers** [comment]
I am taking a break from this issue this week. I'm going back to it after Ecoop, probably.

**Comment by kruegers** [comment]
On hold til we get a new idea how to solve this.

**Comment by johspaeth** [comment]
We have not yet tried to start with an empty grammar and a Xtext project which we first tie to CryptoAnalysis and then work our way back to full CrySL syntax. I guess that would be worth trying. What do you think?

**Comment by kruegers** [comment]
Yes, I agree. That makes sense. @gokcekrky, could you please take a look at this?
