### ISSUE TITLE
Updated PBEKeySpec rule only allows iterationCount = 10000, but not larger.

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/CryptoAnalysis#62]
After [the rule set was updated](https://github.com/CROSSINGTUD/CryptoAnalysis/commit/aeabd21c8fac213841691541188895e97b651ee3), the PBEKeySpec rule only allows iterationCount == 10000 but no value larger and some test fail. Therefore, I [reverted](https://github.com/CROSSINGTUD/CryptoAnalysis/commit/be7bbfefdcb8c7148b5328e1014d638f64befa06) the binary file of the PBEKeySpec rule in the master.

It is weird, as [the source code of the rule](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/master/src/de/darmstadt/tu/crossing/PBEKeySpec.cryptsl) allows >= 10000. Was the correct `crypslbin` file committed?

**Comment by kruegers** [comment]
Not sure, what the exact problem was, but part of it was that I had increased the iteration count for PBEKeySpec and PBEParameterSpec and removed .../GCM/PKCS5Padding from the set of allowed configurations, but had forgotten to update the corresponding test cases. That is done now and there are no more errors related to PBEKeySpec as far as I can tell.

**Comment by johspaeth** [comment]
Is this really fixed now? [Check my comment here](https://github.com/CROSSINGTUD/CryptoAnalysis/commit/161f2a5f9e3c2ff5c3ed2a507ee79fae3b006487#diff-a8fb69b7779354d023dd0864f3e33788R658)

**Comment by kruegers** [comment]
Ah, thanks for the hint. I was experimenting with the numbers to figure out whether the original problem still existed and missed to correct them all before committing.
