### ISSUE TITLE
Test results in Shippable

### ISSUE THREAD

**Issue by kruegers** [CROSSINGTUD/CryptoAnalysis#64]
Add support for test-results summaries in shippable. 

[It already works for CogniCrypt.](https://app.shippable.com/github/CROSSINGTUD/CogniCrypt/runs/633/1/tests) Feel free to check out how it works there.

**Comment by enriozuni** [comment]
Succeeded generating test reports in Shippable CI using the Surefire Maven plugin, similar way like it was used in CogniCrypt

**Comment by johspaeth** [comment]
Thanks a lot!

**Comment by enriozuni** [comment]
You are welcome
