### ISSUE TITLE
Ground Truth for Artifacts on maven central

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/CryptoAnalysis#66]
- [x] Automatic execute of the analysis on an artifact of maven central by supplying: GroupId, ArtifactId and Version.
- [x] Specify results for at least 10 artifacts in form of False Positive, False Negatives and True Positives

**Comment by johspaeth** [comment]
Here is the list of artifacts (groupId artifactId version) to specify

- [ ] com.github.emc-mongoose mongoose-storage-driver-atmos 0.1.6
- [ ] de.unkrig.commons commons-lang 1.2.11
- [ ] io.rubrica rubrica 0.1.8
- [ ] com.github.t3t5u common-util 1.0.0
- [ ] com.github.kcjang scmutil 1.0.2.2
- [ ] com.google.code.spring crypto-utils-spring-crypto-utils 1.4.0

**Comment by sritejakv** [comment]
Added all the required code in [here](https://github.com/CROSSINGTUD/CryptoAnalysis/tree/issue-%2366-ground-truth-for-artifacts-on-maven/CryptoAnalysis/src/test/java/test/maven) for all the packages mentioned above with respective true positives, false positives and false negatives [found](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/issue-%2366-ground-truth-for-artifacts-on-maven/CryptoAnalysis/src/test/java/test/maven/MavenTestData.java)
