### ISSUE TITLE
Update Dependencies to WPDS' Snapshot Versions

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/CryptoAnalysis#67]
The maven dependency [WPDS](https://github.com/CROSSINGTUD/WPDS) is now hosted on [soot's own repository](https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/). 

- [x] Update the dependency to WPDS to the snapshots
- [x] Update Readme.md accordingly.

**Comment by mbruns42** [comment]
- [ ]  Remove WPDS build from shippleable.yml
