### ISSUE TITLE
Automate Android tests

### ISSUE THREAD

**Issue by smeyer198** [CROSSINGTUD/CryptoAnalysis#690]
#689 added (old) tests for the `HeadlessAndroidScanner`. Running them requires an Android SDK. However, since they are licensed and rather large, they cannot be uploaded to the GitHub remote directly, that is, they have to be added to the local platforms directory manually.

Task: Research whether it is possible to run the Android tests in an action on GitHub. More precisely, is it possible to fetch an Android SDK and run the tests with it. If possible, implement a corresponding action.

**Comment by svenfeld** [comment]
This action facilitates the setup of the sdkmanager which is required for Android CI pipelines https://github.com/android-actions/setup-android. The sdkmanager is also used to accept the required licenses for headless applications.

See the following links for more information.

https://developer.android.com/studio/projects/continuous-integration

https://developer.android.com/tools/sdkmanager

**Comment by svenfeld** [comment]
PR #735 adds the necessary functionality to run the Android tests in a Github Action. However, the tests are failing for unknown reason.
