### ISSUE TITLE
NeverTypeOf constraints not checked correctly

### ISSUE THREAD

**Issue by kruegers** [CROSSINGTUD/CryptoAnalysis#81]
In the code snippet 
		
	byte [] next = new byte[32];
	SecureRandom secureRandom = SecureRandom.getInstance("SHA1PRNG");
	secureRandom.nextBytes(next);
	PBEKeySpec pBEKeySpec = new PBEKeySpec("password".toCharArray(), next, 10299, 128);

the analysis should detect a violation of the [neverTypeOf](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/master/src/de/darmstadt/tu/crossing/PBEKeySpec.cryptsl#L20) constraint, but it does not.

**Comment by johspaeth** [comment]
@kruegers  
I tried to reproduce the error, but the analysis correctly reported:


	 in Method: void main(java.lang.String[])
		IncompleteOperationError violating CrySL rule for javax.crypto.spec.PBEKeySpec (on Object #5c68438865019e3eaf83d0f728b0a0a3a38ed23dc8111f39d94c4893c4eefa7c)
			Operation on object of type javax.crypto.spec.PBEKeySpec object not completed. Expected call to clearPassword
			at statement: specialinvoke $r4.<javax.crypto.spec.PBEKeySpec: void <init>(char[],byte[],int,int)>($r6, r1, 10299, 128)

		NeverTypeOfError violating CrySL rule for javax.crypto.spec.PBEKeySpec (on Object #5c68438865019e3eaf83d0f728b0a0a3a38ed23dc8111f39d94c4893c4eefa7c)
			First parameter (with value "password") should never be of type java.lang.String.
			at statement: specialinvoke $r4.<javax.crypto.spec.PBEKeySpec: void <init>(char[],byte[],int,int)>($r6, r1, 10299, 128)`

**Comment by kruegers** [comment]
Weird. I was writing a test case for that while describing the issue here and the analysis did not find it. After your comment, I cleaned the project and tried again and now it finds it, too. Let me check, whether the plugin finds it as well.

**Comment by kruegers** [comment]
Ok, works in the plugin, too. I'm closing this issue here then.

**Comment by kruegers** [comment]
Ah, I had the wrong example. The following does not work.
=====NO REPORT==========

	public void encryptData(byte[] plainText) throws GeneralSecurityException {
		generateKey( "ppass");
	}
	
	private SecretKey generateKey(String password) throws GeneralSecurityException {
		PBEKeySpec pBEKeySpec = new PBEKeySpec(password.toCharArray(), salt, 10000, 256);
		SecretKeyFactory secretKeyFactory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256");
		byte[] keyMaterial = secretKeyFactory.generateSecret(pBEKeySpec).getEncoded();
		SecretKey encryptionKey = new SecretKeySpec(keyMaterial, "AES");
		// pBEKeySpec.clearPassword();
		return encryptionKey;
	}
However, when I extract the String "ppass" into a separate variable, CogniCrypt does report the neverTypeOf misuse.
=====CORRECT REPORT==========
	public void encryptData(byte[] plainText, String password) throws GeneralSecurityException {
		String password2 = "ppass";
		generateKey(password2);
	}

I've updated the [test case](https://github.com/CROSSINGTUD/CryptoAnalysis/commit/a0555f7115889f8bc8ddde6f4bf695abd3904a05) accordingly.

**Comment by johspaeth** [comment]
@kruegers I prepared a test case, the first incorrectly generated predicate appears in [this line](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/409728444ed834689c21cea1d5afffb0b660b723/CryptoAnalysis/src/test/java/tests/pattern/UsagePatternTest.java#L1083).

**Comment by johspaeth** [comment]
The origin of the problem is that [this line](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/409728444ed834689c21cea1d5afffb0b660b723/CryptoAnalysis/src/test/java/tests/pattern/UsagePatternTest.java#L1082) is considered as a [seed](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/f10712c48cf564e3b45249380ff82f59e028ce40/CryptoAnalysis/src/main/java/crypto/analysis/CryptoScanner.java#L121) statement, *no matter if the previous statement ensures the predicate.*

**Comment by sritejakv** [comment]
Hi Johannes, I have added the test cases for cipher failing for nested methods in HeadlessTests.java ([issue66.issueOne.simplified](https://github.com/CROSSINGTUD/CryptoAnalysis/tree/issue-%2366-ground-truth-for-artifacts-on-maven/CryptoAnalysisTargets/ReportedIssues/src/issue66/issueOne/simplified)) #66
