### ISSUE TITLE
Adding new methods to KeyStore.crysl

### ISSUE THREAD

**Issue by sritejakv** [CROSSINGTUD/CryptoAnalysis#83]
Currently KeyStore.crysl contains constraints only for one setter - setEntry.  I came across an implementation in one of the jar files (commons-lang) in #66, where they are using setKeyEntry method as setter. Since it is not in the specification, analysis throws TypestateError which is a false positive. Along with setKeyEntry there is another setter setCertificateEntry which can also be added in the KeyStore crysl specification. ([KeyStore documentation](https://docs.oracle.com/javase/7/docs/api/java/security/KeyStore.html))

**Comment by johspaeth** [comment]
Thanks for reporting.

Could you please prepare a pull request for [the rule](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/master/src/de/darmstadt/tu/crossing/KeyStore.cryptsl).

To modify the rules, install the [eclipse plugin CogniCrypt](https://github.com/CROSSINGTUD/CogniCrypt). When installed you can modify `.cryptsl` files in Eclipse and you get support for syntax highlighting and checking.

**Comment by sritejakv** [comment]
I have added the code in [Crypto-API-Rules](https://github.com/CROSSINGTUD/Crypto-API-Rules/tree/issue-83). We also need to update the crysl binaries in CryptoAnalysis project

**Comment by johspaeth** [comment]
@kruegers Could you quickly update the binary files?

**Comment by kruegers** [comment]
Wrong branch.
