### ISSUE TITLE
False Positive reported for MessageDigest

### ISSUE THREAD

**Issue by sritejakv** [CROSSINGTUD/CryptoAnalysis#85]
For the following code snippet, the analysis reports false positive TypestateError.
<img width="485" alt="screen shot 2018-09-11 at 10 22 50 am" src="https://user-images.githubusercontent.com/38907381/45347546-b0cc9500-b5ac-11e8-8cc3-5ddb39c8cd9a.png">

**Comment by johspaeth** [comment]
Thanks, is the typestate error reported if you remove the `try catch` block and add declare the exception in the `throws` part instead?

**Comment by sritejakv** [comment]
The issue is with the for loop in which md.update() is called. If the loop is removed, the analysis doesn't throw any TypestateError. But if md.update() is in the loop, then it throws a TypestateError.

**Comment by sritejakv** [comment]
Here, the for loop is converted into if and else statements in jimple. So there exists a path to md.digest() without md.update(). The analysis reports typestate error in this path. So, this is a True Positive.
