### ISSUE TITLE
Error testing a predicate of Google Tink specification

### ISSUE THREAD

**Issue by rbonifacio** [CROSSINGTUD/CryptoAnalysis#92]
The following test case is failing, because a predicate to the key template object (kt) is not being generated.  

```Java
@Test
public void generateNewAES128GCMKeySet() throws GeneralSecurityException {
  KeyTemplate kt = AeadKeyTemplates.createAesGcmKeyTemplate(16);
  KeysetHandle ksh = KeysetHandle.generateNew(kt);
  Assertions.hasEnsuredPredicate(kt);
  Assertions.mustBeInAcceptingState(kt);
  Assertions.mustBeInAcceptingState(ksh);		
}
```

The goal here is to verify if the [specification for the class AeadKeyTemplates](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/master/src/de/darmstadt/tu/crossing/tink/AeadKeyTemplates.cryptsl) is correct. The Google Tink specifications are available at the [Crypto-API-Rules repository](https://github.com/CROSSINGTUD/Crypto-API-Rules/tree/master/src/de/darmstadt/tu/crossing/tink)

The test code is available at the branch issue-89. To run this test cases, it is necessary to configure Soot to find the Google Tink libraries. To this end, we have to add these lines

```Java 
String userHome = System.getProperty("user.home");
//... 
sootCp += File.pathSeparator + userHome + "/.m2/repository/com/google/crypto/tink/tink/1.2.0/tink-1.2.0.jar";
```

to the method initializeSootWithEntryPoint (class AbstractTestingFramework of the WPDS project).

**Comment by johspaeth** [comment]
@rbonifacio Could you grant me access to the binary files of the rules? That would easy the testing on my side.

**Comment by rbonifacio** [comment]
@johspaeth the binary files are available in a particular branch [issue-89](https://github.com/CROSSINGTUD/CryptoAnalysis/tree/issue-89/CryptoAnalysis/src/test/resources)

**Comment by johspaeth** [comment]
Regarding (a): I agree, it is confusing especially as we do warn the CrySL developer about this issue. There are only one or two lines in the code that use the actual filename of the rule, we should instead use the string listed in the SPEC clause at these points. 

(b) That seems like a bug. I investigate it further.

**Comment by johspaeth** [comment]
I had a quick look. In my environment, the test cases in `TestAEADCipher` still fail. (I assumed you commited the binary rules into the repository, correct?)

Also, as of now, the analysis does not properly model the static field flows.
It eases debugging and specification, when you explicitly create the object your self by replacing this line
(1) `KeyTemplate kt = AeadKeyTemplates.AES128_GCM;`
by
(2) `KeyTemplate kt = AeadKeyTemplates.createAesGcmKeyTemplate(16);`

The simple difference is that by unsing the first line, the JVM implicitly calls the class initializer (<clinit>) of `AedKeyTemplates` and within the class initializer, it creates the object
`AeadKeyTemplates.AES128_GCM = AeadKeyTemplates.createAesGcmKeyTemplate(16);` 

The test cases do not properly model the <clinit> calls as they are not explicit within the code. I work on that and give you an update here. Until then line (2) in your test cases.

**Comment by rbonifacio** [comment]
I've just updated and built the WPDS project. Now I am getting the same results as yours (some test cases are failing). At least this might explain the different results that we were getting.

**Comment by johspaeth** [comment]
Good...or well bad. :)

Then I know where to look at.

**Comment by johspaeth** [comment]
While debuggnig, I still saw that the constraints lists
[key16 == 16 , key32 == 32] which yields to the problem discussed above.

Did you update the rules (and cryptslbin files) accordingly? In the repository, I cannot see any update on the master:
https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/master/src/de/darmstadt/tu/crossing/tink/AeadKeyTemplates.cryptsl

We really need to be able to read in rules in CrySL-source code format...Stefan is working on that!
