### ISSUE TITLE
update soot dependency

### ISSUE THREAD

**Issue by linghuiluo** [CROSSINGTUD/CryptoAnalysis#96]
Can you please update the soot dependency to the newest release version 3.1.0? Also all the WPDS soot dependencies, otherwise i will get bugs in boomerang when use CrypoAnalysis in project which depends on the soot 3.1.0, since it is not compatible with 3.0.0.

**Comment by linghuiluo** [comment]
@johspaeth

**Comment by johspaeth** [comment]
I updated the soot dependencies, the changes are on the master.
Though, the update leads to the CI-service (Jenkins) to crash in a `java.lang.NoSuchMethodError: soot.jimple.JimpleBody.getUnits()Lsoot/PatchingChain;`. On my own machine, and my machine at work, the build and test pass.
@mbenz89 @linghuiluo Do you have any idea what could go wrong? Was there a change in these classes from 3.0.0 to 3.1.0?

**Comment by mbenz89** [comment]
It seems that the method has changed to return `UnitPatchingChain` instead of `PatchingChain`: `https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/jdoc/`

**Comment by johspaeth** [comment]
Thanks @mbenz89 for fixing the Jenkins server. @linghuiluo a `mvn clean` should solve the issue on your machine.

**Comment by linghuiluo** [comment]
@johspaeth thanks for upgrading the version!
